FROM php:7.0-apache
#DockerHub üzerinde bulunan php:7.0-apache sürümü belirlendi.
#https://hub.docker.com/_/php üzerinden
COPY ./source/index.php /var/www/html/index.php
# source klasörü içerisinde bulunan index.php dosyasını container içerisinde ki /var/www/html/index.php  klasörü içerisine kopyalandı.