FROM php:7.0-apache
#DockerHub üzerinde bulunan php:7.0-apache sürümü belirlendi.
#https://hub.docker.com/_/php üzerinden
COPY ./source/ /var/www/html/
# source klasörü içerisinde bulunan dosyalar container içerisinde ki /var/www/html/ klasörüne kopyalandı.